### ISSUE TITLE
efibootmgr -c does not add entry to BootOrder unless efibootmgr -O is run first

### ISSUE THREAD

**Issue by marja11** [rhinstaller/efibootmgr#24] opened 2015-03-15 22:32 UTC
Version: efibootmgr-0.11.0-3.mga5

Often, when updating efibootmgr or reinstalling the efi bootloader, Mageia disappears from the BootOrder list.

In grub2 logs we see
"efibootmgr: Could not add entry to BootOrder: File exists"

Which is the same error as we have here
[root@denkblok3 marja]# efibootmgr -c -d /dev/sda -p 2 -w -L mageia -l \EFI\mageia\grubx64.efi 
efibootmgr: Could not add entry to BootOrder: File exists
[root@denkblok3 marja]#

Which occurs after running 
efibootmgr -b (boot entry) -B
not only when there are entries left in the BootOrder list, but even when the removed entry was the only one, so that there are none left.

It does _not_ occur after running 
efibootmgr -O
unfortunately that is not a solution, because then all other BootOrder entries get lost.

However, it does _also_ occur after then running
efibootmgr -o (only the other wanted boot order entries)

**Comment by marja11** [comment] 2015-03-15 22:33
sorry for the horrid lay out of my comment :-(

**Comment by vathpela** [comment] 2015-03-20 20:34
Can you strace the -c invokation for me?

**Comment by barjac** [comment] 2015-03-20 22:50
[root@localhost baz]# strace efibootmgr -c -d /dev/sda -p 2 -w -L mageia -l \EFI\mageia\grubx64.efi 
execve("/usr/sbin/efibootmgr", ["efibootmgr", "-c", "-d", "/dev/sda", "-p", "2", "-w", "-L", "mageia", "-l", "EFImageiagrubx64.efi"], [/* 60 vars */]) = 0
brk(0)                                  = 0x225e000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd3934c7000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=54358, ...}) = 0
mmap(NULL, 54358, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fd3934b9000
close(3)                                = 0
open("/lib64/libpci.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260#\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=50176, ...}) = 0
mmap(NULL, 2143472, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd39309d000
mprotect(0x7fd3930a8000, 2093056, PROT_NONE) = 0
mmap(0x7fd3932a7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7fd3932a7000
close(3)                                = 0
open("/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220#\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=110384, ...}) = 0
mmap(NULL, 2204200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd392e82000
mprotect(0x7fd392e9c000, 2093056, PROT_NONE) = 0
mmap(0x7fd39309b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7fd39309b000
close(3)                                = 0
open("/lib64/libefivar.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\32\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=50696, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd3934b8000
mmap(NULL, 2145560, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd392c76000
mprotect(0x7fd392c7b000, 2097152, PROT_NONE) = 0
mmap(0x7fd392e7b000, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7fd392e7b000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\0\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2037336, ...}) = 0
mmap(NULL, 3878784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd3928c3000
mprotect(0x7fd392a6d000, 2093056, PROT_NONE) = 0
mmap(0x7fd392c6c000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a9000) = 0x7fd392c6c000
mmap(0x7fd392c72000, 16256, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd392c72000
close(3)                                = 0
open("/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@:\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=94976, ...}) = 0
mmap(NULL, 2198344, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd3926aa000
mprotect(0x7fd3926c0000, 2093056, PROT_NONE) = 0
mmap(0x7fd3928bf000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7fd3928bf000
mmap(0x7fd3928c1000, 6984, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd3928c1000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd3934b7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd3934b6000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd3934b5000
arch_prctl(ARCH_SET_FS, 0x7fd3934b6700) = 0
mprotect(0x7fd392c6c000, 16384, PROT_READ) = 0
mprotect(0x7fd3928bf000, 4096, PROT_READ) = 0
mprotect(0x7fd392e7b000, 4096, PROT_READ) = 0
mprotect(0x7fd39309b000, 4096, PROT_READ) = 0
mprotect(0x7fd3932a7000, 4096, PROT_READ) = 0
mprotect(0x60e000, 4096, PROT_READ)     = 0
mprotect(0x7fd3934c8000, 4096, PROT_READ) = 0
munmap(0x7fd3934b9000, 54358)           = 0
access("/sys/firmware/efi/efivars/", F_OK) = 0
statfs("/sys/firmware/efi/efivars/", {f_type=0xde5e81e4, f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096}) = 0
openat(AT_FDCWD, "/sys/firmware/efi/efivars/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
brk(0)                                  = 0x225e000
brk(0x2287000)                          = 0x2287000
fcntl(3, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
getdents(3, /* 42 entries */, 32768)    = 2848
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
open("/sys/firmware/efi/efivars/Boot0000-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_RDONLY) = 3
read(3, "\7\0\0\0", 4)                  = 4
read(3, "\1\0\0\0\36\0E\0F\0I\0 \0D\0V\0D\0/\0C\0D\0R\0O\0M\0"..., 1024) = 64
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/sys/firmware/efi/efivars/Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_RDONLY) = 3
read(3, "\7\0\0\0", 4)                  = 4
read(3, "\1\0\0\0 \0E\0F\0I\0 \0H\0a\0r\0d\0 \0D\0r\0i\0v\0"..., 1024) = 68
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/sys/firmware/efi/efivars/Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_RDONLY) = 3
read(3, "\7\0\0\0", 4)                  = 4
read(3, "\1\0\0\0 \0E\0F\0I\0 \0H\0a\0r\0d\0 \0D\0r\0i\0v\0"..., 1024) = 72
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/sys/firmware/efi/efivars/Boot0003-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_RDONLY) = 3
read(3, "\7\0\0\0", 4)                  = 4
read(3, "\1\0\0\0000\0E\0F\0I\0 \0I\0n\0t\0e\0r\0n\0a\0l\0 \0"..., 1024) = 92
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/dev/sda", O_RDWR)                = 3
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "\353H\220\0\0\0GRUB\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 512) = 512
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(8, 0), ...}) = 0
uname({sys="Linux", node="localhost", ...}) = 0
ioctl(3, BLKGETSIZE64, 16106127360)     = 0
ioctl(3, BLKSSZGET, 512)                = 0
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 512, SEEK_SET)                 = 512
read(3, "EFI PART\0\0\1\0\\\0\0\0\26\350\237M\0\0\0\0\1\0\0\0\0\0\0\0"..., 512) = 512
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 1024, SEEK_SET)                = 1024
read(3, "\257=\306\17\203\204rG\216y=i\330G}\344\352A\322\302K\210\232A\272HL$\223Gs\261"..., 16384) = 16384
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 16106126848, SEEK_SET)         = 16106126848
read(3, "EFI PART\0\0\1\0\\\0\0\0\253\247\355Y\0\0\0\0\377\377\337\1\0\0\0\0"..., 512) = 512
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 16106110464, SEEK_SET)         = 16106110464
read(3, "\257=\306\17\203\204rG\216y=i\330G}\344\352A\322\302K\210\232A\272HL$\223Gs\261"..., 16384) = 16384
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "\353H\220\0\0\0GRUB\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 512) = 512
close(3)                                = 0
open("/dev/sda", O_RDWR)                = 3
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "\353H\220\0\0\0GRUB\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 512) = 512
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(8, 0), ...}) = 0
uname({sys="Linux", node="localhost", ...}) = 0
ioctl(3, BLKGETSIZE64, 16106127360)     = 0
ioctl(3, BLKSSZGET, 512)                = 0
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 512, SEEK_SET)                 = 512
read(3, "EFI PART\0\0\1\0\\\0\0\0\26\350\237M\0\0\0\0\1\0\0\0\0\0\0\0"..., 512) = 512
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 1024, SEEK_SET)                = 1024
read(3, "\257=\306\17\203\204rG\216y=i\330G}\344\352A\322\302K\210\232A\272HL$\223Gs\261"..., 16384) = 16384
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 16106126848, SEEK_SET)         = 16106126848
read(3, "EFI PART\0\0\1\0\\\0\0\0\253\247\355Y\0\0\0\0\377\377\337\1\0\0\0\0"..., 512) = 512
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 16106110464, SEEK_SET)         = 16106110464
read(3, "\257=\306\17\203\204rG\216y=i\330G}\344\352A\322\302K\210\232A\272HL$\223Gs\261"..., 16384) = 16384
ioctl(3, BLKSSZGET, 512)                = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "\353H\220\0\0\0GRUB\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 512) = 512
close(3)                                = 0
access("/sys/firmware/efi/efivars/Boot0004-8be4df61-93ca-11d2-aa0d-00e098032b8c", F_OK) = -1 ENOENT (No such file or directory)
open("/sys/firmware/efi/efivars/Boot0004-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_WRONLY|O_CREAT|O_EXCL, 0600) = 3
write(3, "\7\0\0\0\1\0\0\0\\\0m\0a\0g\0e\0i\0a\0\0\0\4\1*\0\2\0\0\0"..., 116) = 116
close(3)                                = 0
open("/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_RDONLY) = 3
read(3, "\7\0\0\0", 4)                  = 4
read(3, "\0\0\1\0\2\0\3\0", 1024)       = 8
read(3, "", 1024)                       = 0
close(3)                                = 0
access("/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c", F_OK) = 0
open("/sys/firmware/efi/efivars/BootOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c", O_WRONLY|O_CREAT|O_EXCL, 0600) = -1 EEXIST (File exists)
write(2, "efibootmgr: ", 12efibootmgr: )            = 12
write(2, "Could not add entry to BootOrder", 32Could not add entry to BootOrder) = 32
write(2, ": ", 2: )                       = 2
write(2, "File exists\n", 12File exists
)           = 12
exit_group(6)                           = ?
+++ exited with 6 +++

**Comment by barjac** [comment] 2015-04-02 09:09
Any news on this? 
Please advise if further information is needed to help debug.

**Comment by CaptainFlint** [comment] 2015-04-02 10:54
2developers:
Looks like efi_del_variable before efi_set_variable in the function add_to_boot_order() should do the trick. Maybe, also in set_boot_order().

**Comment by barjac** [comment] 2015-04-02 17:26
Thanks - this seems to work :)

**Comment by atrigent** [comment] 2015-04-23 14:47
This problem is caused by your distribution having an old version of the efivar library. Compare:

http://mageia.madb.org/package/show/application/0/release/cauldron/name/libefivar0
https://github.com/rhinstaller/efivar/releases

The correct fix is for your distribution to update this library.

**Comment by barjac** [comment] 2015-04-25 16:38
Thanks for pointing this out.
We have tested with efivar-0.15 and all seems well without the above patch.

**Comment by vathpela** [comment] 2015-05-27 18:17
With that in mind, I'll close this issue.  Thanks for the debugging, everybody!

**Closed by vathpela** 2015-05-27 18:17 UTC
